AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: states.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: executionrole
    Type: AWS::IAM::Role
  Function:
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1r7iyarib6oy8/sfn-yaml-macro-test/ae3af60093b3f9e554c60c14cdc77c28
      Handler: app.handler
      Runtime: python3.6
      Timeout: 10
    Type: AWS::Serverless::Function
  MyStateMachine:
    Properties:
      DefinitionString:
        Fn::Sub:
        - "{\n  \"Comment\": \"Parallel Example.\",\n  \"StartAt\": \"LookupCustomerInfo\"\
          ,\n  \"States\": {\n    \"LookupCustomerInfo\": {\n      \"Type\": \"Parallel\"\
          ,\n      \"End\": true,\n      \"Branches\": [\n        {\n          \"\
          StartAt\": \"LookupAddress\",\n          \"States\": {\n            \"LookupAddress\"\
          : {\n              \"Type\": \"Task\",\n              \"Resource\": \"${0FnGetAtt}\"\
          ,\n              \"End\": true\n            }\n          }\n        },\n\
          \        {\n          \"StartAt\": \"LookupPhone\",\n          \"States\"\
          : {\n            \"LookupPhone\": {\n              \"Type\": \"Task\",\n\
          \              \"Resource\": \"${1FnGetAtt}\",\n              \"End\": true\n\
          \            }\n          }\n        }\n      ]\n    }\n  }\n}"
        - 0FnGetAtt:
            Fn::GetAtt:
            - Function
            - Arn
          1FnGetAtt:
            Fn::GetAtt:
            - Function
            - Arn
      RoleArn:
        Fn::GetAtt:
        - ExecutionRole
        - Arn
    Type: AWS::StepFunctions::StateMachine
Transform:
- AWS::Serverless-2016-10-31
- SFNYAML
